apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue 
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/catalogue:VERSION
        ports:
        - containerPort: 8080
        envFrom: 
          - configMapRef: 
              name: catalogue-cm 

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-cm
data:
  MONGO_URL: "mongodb://admin1:roboshop1@roboshop-dev.cluster-c93whrwsdihk.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"      

--- 
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    app: catalogue
  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080
    targetPort: 8080


# --- 
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: "nginx.b49-roboshop.store"
#     http:
#       paths:
#       - path: "/"
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx-service
#             port:
#               number: 8080